export default [
  {
    UUID: 'Crystal_Pebble',
    Name: 'Crystal Pebble (Soul/Crystal Sorcery)',
    AP: 2,
    FP: 1,
    Cost: 1,
    Range: '25 foot range',
    Damage: '1d2 magic damage',
    Requirements: '10 Int requirement.',
    Description: 'Fire a small glowing crystal shard toward a target. This spell can pierce through one creature that it hits, continuing up to its maximum range or until it hits a second. Charging this spell allows it to ricochet off of the first target it hits and change direction before flying towards a second (or until it flies a total distance equal to its maximum range).'
  },
  {
    UUID: 'Soul_Arrow',
    Name: 'Soul Arrow (Soul/Crystal Sorcery)',
    AP: 2,
    FP: 1,
    Cost: 1,
    Range: '20 foot range',
    Damage: '1d4 magic damage',
    Requirements: '10 Int requirement.',
    Description: 'Fire a homing arrow of magic at a target. Charging this spell increases its range by 10 feet.'
  },
  {
    UUID: 'Great_Soul_Arrow',
    Name: 'Great Soul Arrow (Soul/Crystal Sorcery)',
    AP: 2,
    FP: 2,
    Cost: 1,
    Range: '20 foot range',
    Damage: '1d8 magic damage',
    Requirements: '14 Int requirement.',
    Description: 'Fire a strong homing arrow of magic at a target. Charging this spell increases its range by 10 feet.'
  },
  {
    UUID: 'Great_Heavy_Soul_Arrow',
    Name: 'Great Heavy Soul Arrow (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 2,
    Cost: 1,
    Range: '20 foot range',
    Damage: '2d8 magic damage',
    Requirements: '15 Int requirement.',
    Description: 'Fire a larger, strong homing arrow of magic at a target. Charging this spell increases its range by 10 feet, and once per charged casting causes it to change direction and follow a target that dodged out of its way, as long as it still has the range to do so.'
  },
  {
    UUID: 'Magic_Weapon',
    Name: 'Magic Weapon (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Run your casting implement along a melee weapon in range to buff it with magic. The wielder of that weapon may add 2d4 magic damage (plus your scaling from this spell), once per round to each creature that they damaged with that weapon. This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration, but does not increase the damage of the buff.'
  },
  {
    UUID: 'Great_Magic_Weapon',
    Name: 'Great Magic Weapon (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '16 Int requirement.',
    Description: 'Run your casting implement along a melee weapon in range to buff it with heavy magic. The wielder of that weapon may add 2d6 magic damage (plus your scaling from this spell), once per round to each creature that they damaged with that weapon. This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration, but does not increase the damage of the buff.'
  },
  {
    UUID: 'Crystal_Magic_Weapon',
    Name: 'Crystal Magic Weapon (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '18 Int requirement.',
    Description: 'Run your casting implement along a melee weapon in range to buff it with crystalized magic. The wielder of that weapon may add 2d8 magic damage (plus your scaling from this spell), once per round to each creature that they damaged with that weapon. This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration, but does not increase the damage of the buff. '
  },
  {
    UUID: 'Magic_Shield',
    Name: 'Magic Shield (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '12 Int requirement.',
    Description: 'Run your casting implement along a shield in range to buff it with a magic barrier. Over the duration of the spell, that shield may block magic damage and also reduce the magic damage it takes when defending by 25\% (before converting to poise damage). This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration. '
  },
  {
    UUID: 'Great_Magic_Shield',
    Name: 'Great Magic Shield (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Run your casting implement along a shield in range to buff it with a magic barrier. Over the duration of the spell, that shield may block magic damage and also reduce the magic damage it takes when defending by 50\% (before converting to poise damage). This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration. '
  },
  {
    UUID: 'Alvina_Hail',
    Name: 'Alvina Hail (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 1,
    Range: '15 foot range',
    Damage: '3d6 magic damage',
    Requirements: '15 Int requirement.',
    Description: 'Fire a small soul projectile up into the air above a space in range. The projectile then bursts and rains down a hail of magic, hitting all grid spaces in a 10ft by 10ft area of your choice below it. Charging this spell increases its range by 10 feet, and increases its area of effect to 15ft by 15ft. '
  },
  {
    UUID: 'Crystal_Hail',
    Name: 'Crystal Hail (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 4,
    Cost: 2,
    Range: '20 foot range',
    Damage: '3d8 magic damage',
    Requirements: '16 Int requirement.',
    Description: 'Fire a small crystal projectile up into the air above a space in range. The projectile then bursts and rains down a hail of magic crystal shards, hitting all grid spaces in a 15ft by 15ft area of your choice below it. Charging this spell causes it to burst and deal its damage again over the same area, on the start of your following turn after it resolves. '
  },
  {
    UUID: 'Crystal_Tether',
    Name: 'Crystal Tether (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '10 foot range',
    Duration: '10 round duration.',
    Requirements: '1d4 magic damage, 15 Int requirement.',
    Description: 'Launch a wrapping crystal rope projectile at a target in range. After casting this spell and hitting two to four creatures or objects within range of yourself and each other, the crystal ropes connect themselves and pull firm. If cast on a creature capable of resisting, they can resist with a DC (12 + your Int mod) athletics check. If successful, their crystal rope does not connect to other targets, but they still take half of this spells magic damage over its duration. \par All targets bound together by the crystal are pulled to be adjacent to each other, and are then unable to move more than 5 feet from each other (but can pull one another if they have the strength to do so). The damage of the spell is taken at the start of each targets turns, and does not benefit from scaling. This spell does not stack with itself, but can be cast again on the same target to refresh its damage and force another check. Charging this spell causes it to fire two crystal rope projectiles at the same time, and increases the DC to resist being bound by 2.'
  },
  {
    UUID: 'Twisted_Wall_of_Crystal',
    Name: 'Twisted Wall of Crystal (Soul/Crystal Sorcery)',
    AP: 6,
    FP: 4,
    Cost: 1,
    Range: '10 foot range',
    Duration: '10 round duration.',
    Requirements: '15 Int requirement.',
    Description: 'Conjure a wall of crystal centered in range that is 3 feet deep, 10 feet tall, and 15 feet long. The wall blocks all movement, physical attacks and projectiles, while allowing all elemental projectiles to pass through. The wall crumbles to crystal dust at the end of its duration, and if any creatures or objects obstruct the wall when cast, the wall does not appear in the obstructed locations. You may have (your Int mod/2) instances of crystal walls from this spell active at a time. Charging this spell increases its range by 5 feet, and increases the length of the wall to 25 feet.'
  },
  {
    UUID: 'Devorac_Crystal_Butterfly',
    Name: 'Devorac\'s Crystal Butterfly (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 1,
    Range: '15 foot range',
    Duration: '3 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Conjure a swarm of crystal butterflies that float above your head for three rounds and attach to the first hostile creature which enters the spells range. The creature then needs to make a DC (12 + your Int mod) perception check or be inflicted with the impaired vision status condition for the next full round of combat. Charging this spell increases the DC by 3.'
  },
  {
    UUID: 'Floating_Soulmasses',
    Name: 'Floating Soulmasses (Soul/Crystal Sorcery)',
    AP: 6,
    FP: 5,
    Cost: 1,
    Range: '20 foot range',
    Duration: '10 round duration.',
    Requirements: '1d6 magic damage, 16 Int requirement.',
    Description: 'Conjure three masses of soul magic which stay floating above your head for the duration of the spell. You may choose to fire any number of them at any target space in range, during your own turn, for no additional AP or FP cost. Each soulmass deals the magic damage of this spell, with the total scaling split between them. Charging this spell adds a fourth soulmass, but does not add extra damage die to the individual soulmasses.'
  },
  {
    UUID: 'Floating_Crystal_Soulmasses',
    Name: 'Floating Crystal Soulmasses (Soul/Crystal Sorcery)',
    AP: 8,
    FP: 6,
    Cost: 2,
    Range: '20 foot range',
    Duration: '10 round duration.',
    Requirements: '1d8 magic damage, 17 Int requirement.',
    Description: 'Conjure three masses of crystal magic which stay floating above your head for the duration of the spell. You may choose to fire any number of them at any target space in range, during your own turn, for no additional AP or FP cost. Each crystal mass deals the magic damage of this spell, with the total scaling split between them. Charging this spell adds two additional crystal masses, but does not add extra damage die to the individual masses.'
  },
  {
    UUID: 'Altia_Soul_Feathers',
    Name: 'Altia\'s Soul Feathers (Soul/Crystal Sorcery)',
    AP: 7,
    FP: 6,
    Cost: 2,
    Range: '20 foot range',
    Duration: '10 round duration.',
    Requirements: '1d6 magic damage, 18 Int requirement.',
    Description: 'Conjure three magical feathers which stay floating above your head for the duration of the spell. You may choose to fire any number of them at any target space in range, during your own turn, for no additional AP or FP cost. Each feather deals the magic damage of this spell, with the total scaling split between them. While any of the feathers still remain floating above you, you may fly at the normal speed of movement but you may not make a dodge action while flying above the ground with this spell. Charging this spell adds a fourth magic feather, but does not add extra damage die to the individual feathers.'
  },
  {
    UUID: 'Soul_Spear',
    Name: 'Soul Spear (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 1,
    Range: '40 foot range',
    Damage: '4d10 magic damage',
    Requirements: '18 Int requirement.',
    Description: 'Fire a massive projectile of soul magic toward a target in range. This spell can pierce through one creature that it hits, continuing up to its maximum range or until it hits a second. Charging this spell allows it to also pierce through one object or source of cover no thicker than 5 feet, without dissipating.'
  },
  {
    UUID: 'Crystal_Soul_Spear',
    Name: 'Crystal Soul Spear (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 2,
    Range: '40 foot range',
    Damage: '6d10 magic damage',
    Requirements: '20 Int requirement.',
    Description: 'Fire a massive projectile of crystal magic toward a target in range. This spell can pierce through up to two creatures that it hits, continuing up to its maximum range or until it hits a third. Charging this spell allows it to also pierce through one object or source of cover no thicker than 10 feet, without dissipating.'
  },
  {
    UUID: 'Soul_Stream',
    Name: 'Soul Stream (Soul/Crystal Sorcery)',
    AP: 5,
    FP: 4,
    Cost: 2,
    Range: '60 foot range',
    Damage: '8d10 magic damage',
    Requirements: '22 Int requirement.',
    Description: 'Fire a torrential beam of magic, hitting all spaces in a line up to the spells maximum range. All creatures struck by this spell must make a DC (14 + your Int mod) athletics check or be knocked prone. Charging this spell also increases its FP cost by 2, but increases the size of the beam, giving it a thickness of 10 feet, and increasing its range by 10 feet.'
  },
  {
    UUID: 'Alvina_Flashsword',
    Name: 'Alvina Flashsword (Soul/Crystal Sorcery)',
    AP: 3,
    FP: 1,
    Cost: 1,
    Range: '5 foot range',
    Damage: '1d6 magic damage',
    Requirements: '13 Int requirement.',
    Description: 'Conjure a magic sword out of your staff and swing it at a target in range. Attacking with this spell also counts as using a Straight Sword for the sake of weapon feats. Charging this spell increases the length of the blade, increasing its range to 10 feet, and causing it to do 3 poise damage to any creature it hits.'
  },
  {
    UUID: 'Soul_Greatsword',
    Name: 'Soul Greatsword (Soul/Crystal Sorcery)',
    AP: 4,
    FP: 1,
    Cost: 1,
    Range: '5 foot range',
    Damage: '1d8 magic damage',
    Requirements: '14 Int requirement.',
    Description: 'Conjure a magic great sword out of your staff and swing it at a target in range. Attacking with this spell also counts as using a Great Sword for the sake of weapon feats. Charging this spell increases the length of the blade, increasing its range to 10 feet, and causing it to do 4 poise damage to any creature it hits.'
  },
  {
    UUID: 'Drain_Heat',
    Name: 'Drain Heat (Frost Sorcery)',
    AP: 4,
    FP: 2,
    Cost: 1,
    Range: '5 foot range',
    Duration: '2 round duration.',
    Requirements: '12 Int requirement.',
    Description: 'Swing your casting implement, pulling from a creature in range and toward yourself to steal away their heat and use it as a weak shield to fire. The target creature must make a DC (10 + your Int mod) firekeeping check or take 2d2 frost build up and have each instance of frost build up they take over the next two rounds be increased by +1. As well, over that same duration, you may increase your fire damage resistance by one tier. You may only have one instance of this spell active at a time and casting it on a new creature ends its effects on the previous. This spell may also be cast on a very warm ally to cool them off, on a small amount of food to preserve it for a time, or on a small fire to put it out. Charging this spell increases the DC by 2 and the frost build up to 3d2. '
  },
  {
    UUID: 'Cold_Burst',
    Name: 'Cold Burst (Frost Sorcery)',
    AP: 2,
    FP: 2,
    Cost: 1,
    Range: '15 foot range',
    Damage: '1d6 magic damage',
    Requirements: '13 Int requirement.',
    Description: 'Summon a bursting ball of magic ice in a target location in range, dealing magic damage and 1d2 frost status build up in that grid space. Any creature damaged by this spell which is already frostbitten instead takes 1d8 magic damage. Charging this spell increases its range by 5 feet, and increases its frost build up to 2d2. '
  },
  {
    UUID: 'Frozen_Weapon',
    Name: 'Frozen Weapon (Frost Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Run your casting implement along a melee weapon in range to buff it with a frost aura. The wielder of that weapon may add 2d2 frost status build up, once per round to each creature that they damaged with that weapon. This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration.'
  },
  {
    UUID: 'Snap_Freeze',
    Name: 'Snap Freeze (Frost Sorcery)',
    AP: 4,
    FP: 2,
    Cost: 1,
    Range: '25 foot range',
    Duration: '2 round duration.',
    Requirements: '15 Int requirement.',
    Description: 'Blast a 15 foot wide cylinder of cold in front of you that stays in place for two rounds (12 seconds) reaching up to the spells maximum range. Any creature which begins their turn within the cylinder, or moves into one of its spaces takes 1d4 frost status build up. Creatures which are already frostbitten instead lose 1d2 FP each time they would have taken from build up from this spell. Only one instance of this spell may be active at a time, and casting a new one dissipates the old. Charging this spell causes it to instead produce a 25 foot cone.'
  },
  {
    UUID: 'Cryo_Flesh',
    Name: 'Cryo Flesh (Frost Sorcery)',
    AP: 4,
    FP: 4,
    Cost: 2,
    Range: 'Self cast',
    Duration: '5 round duration.',
    Requirements: '16 Int requirement.',
    Description: 'Lift your casting implement in the air and bring it down toward the ground in a gust of cold wind, encasing yourself in a deep armor of ice. This deals 1d20 + 2 frost status build up to you, but gives one tier of physical resistance, one tier of resistance to all elements except fire. As well, deal 1d2 frost status to all creatures which begin or end their turn within 5 feet of you for the duration of the spell. This spell can only be cast when you are not already inflicted with frostbite, and lasts for five rounds (30 seconds). This spell does not stack with any other "flesh" spells. Charging this spell changes the self inflicted frost build up to 2d12 + 2, but instead gives two tiers of physical resistance and deals its 1d2 frost to all creatures which begin or end their turn within 10 feet of you for the duration.'
  },
  {
    UUID: 'Icicle_Spear',
    Name: 'Icicle Spear (Frost Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 1,
    Range: '35 foot range',
    Damage: '4d8 magic damage',
    Requirements: '17 Int requirement.',
    Description: 'Hurl a spear of ice which explodes on contact, dealing its damage to any creature in the targeted location, as well as all adjacent grid spaces. All creatures damaged by this spell also take 1d6 frost build up. Charging this spell increases its range by 5 feet and causes it to deal 2 poise damage to already frostbitten creatures damaged by it.'
  },
  {
    UUID: 'Vanda_Ice_Storm',
    Name: 'Vanda Ice Storm (Frost Sorcery)',
    AP: 4,
    FP: 5,
    Cost: 2,
    Range: '20 foot range',
    Duration: '3 round duration.',
    Requirements: '4d6 magic damage, 20 Int requirement.',
    Description: 'Summon a swirling storm of cold effecting all grid spaces within 20 feet of you when first cast. Upon casting, everything in the area takes the spells damage as well as 2d4 frost status build up. At the beginning of your turn for the next three rounds after its initial casting, everything within that same area takes another 2d4 frost build up. If already frostbitten, creatures must treat the area effected by the spell as difficult terrain and take one poise damage instead of the frost build up. This spell does not effect its caster, but you may only have one instance of this spell active at a time and it cannot be canceled by its caster. Charging this spell increases its range to 30 feet and increases its frost build up to 2d6.'
  },
  {
    UUID: 'Spook',
    Name: 'Spook (Assassin/Light Sorcery)',
    AP: 3,
    FP: 2,
    Cost: 1,
    Range: '5 foot range',
    Duration: '4 round duration.',
    Requirements: '10 Int requirement.',
    Description: 'Created a cloud of magic over your feet, masking any sound and reducing fall damage by half. Increases stealth by +4 when active, and lasts for four rounds (24 seconds). Charging this spell allows you to glide more easily along the ground, giving you one AP of free movement on every round that this spell is active.'
  },
  {
    UUID: 'Mimic_Odor',
    Name: 'Mimic Odor (Assassin/Light Sorcery)',
    AP: 2,
    FP: 1,
    Cost: 1,
    Range: '30 foot range',
    Duration: '2 round duration.',
    Requirements: '11 Int requirement.',
    Description: 'Conjure an odor of your choice, originating from a surface or object within range that is no larger than medium size. This odor persists for two rounds (12 seconds) and must be of something that you are somewhat familiar with, or are able to concentrate on while casting. Charging this spell causes the odor to persist for 10 minutes or until you choose it to end prior to the 10 minutes elapsing.'
  },
  {
    UUID: 'Aural_Decoy',
    Name: 'Aural Decoy (Assassin/Light Sorcery)',
    AP: 2,
    FP: 2,
    Cost: 1,
    Range: '40 foot range',
    Duration: '2 round duration.',
    Requirements: '12 Int requirement.',
    Description: 'Conjure a pulsing rhythmic sound of your choice, originating from a surface in range. This sound persists for two rounds (12 seconds). Charging this spell allows you to add words or more complex sounds to it, but they may not last any longer than the duration of the spell.'
  },
  {
    UUID: 'Betraying_Dart',
    Name: 'Betraying Dart (Assassin/Light Sorcery)',
    AP: 2,
    FP: 2,
    Cost: 1,
    Range: '25 foot range',
    Damage: '1d4 magic damage',
    Requirements: '13 Int requirement.',
    Description: 'Target a space directly behind a creature in range and pull your casting implement toward yourself to conjure a silent portal in the target location. The portal then fires a dark blue magic projectile into the back of the creature. This spell always hits the creature from behind and still hits if they dodge into the space of the portal. Charging this spell increases its range to 35 feet.'
  },
  {
    UUID: 'Cast_Light',
    Name: 'Cast Light (Assassin/Light Sorcery)',
    AP: 3,
    FP: 2,
    Cost: 1,
    Range: 'Self cast',
    Duration: '4 round duration.',
    Requirements: '10 Int requirement.',
    Description: 'Create an orb of magic over your head which glows, lighting up a 30 foot area around you with magical light. This light lasts for four rounds (24 seconds). Charging this spell increases the lit area up to 50 feet, and doubles its duration.'
  },
  {
    UUID: 'Translucence',
    Name: 'Translucence (Assassin/Light Sorcery)',
    AP: 8,
    FP: 2,
    Cost: 1,
    Range: '5 foot range',
    Duration: '10 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Move your casting implement along a visible surface to make that material translucent from only your position/angle of view. This spell is effective up to a depth of 10 feet in that material, and works on a 5ft by 5ft square. Does not have any effect on living tissue. The translucence lasts for one minute. Charging this spell increases its effective depth to 15 feet in non living material, and allows it to be cast on living flesh. Casting the charged version of this spell on living flesh instead gives you insight on the constitution of the target creature, revealing their current maximum HP to you at the time of casting (Some living flesh may be immune to this effect).'
  },
  {
    UUID: 'Telepathy',
    Name: 'Telepathy (Assassin/Light Sorcery)',
    AP: 3,
    FP: 7,
    Cost: 1,
    Range: '5 foot range',
    Duration: '10 round duration.',
    Requirements: '15 Int requirement.',
    Description: 'Create a twisting current of light between yourself and a willing creature in range. As long as you and the creature share a verbal form of communication, and you do not move farther than 100 feet from each other, you may communicate telepathically over the duration of the spell. Other creatures which can make a DC (16+ your Int mod) perception check will be able to see the faint bending light between you and the target of this spell. Charging this spell increases its duration to 30 minutes.'
  },
  {
    UUID: 'Powdered_Light',
    Name: 'Powdered Light (Assassin/Light Sorcery)',
    AP: 3,
    FP: 5,
    Cost: 1,
    Range: 'Self cast',
    Duration: '10 round duration.',
    Requirements: '15 Int requirement.',
    Description: 'Move your casting implement in a circular motion above your head to deposit a glowing powdered light over yourself. For ten rounds (one minute), or until you take damage of any kind, you may create the illusion that you look like any object around you that you can see. This object must be approximately small or medium sized (no smaller than a cat and no larger than a tall humanoid). You may only move slowly without breaking the illusion (performing only basic movement actions, no dodging or sprinting), and the illusion does not mask any sound you produce. Charging this spell increases its duration to ten minutes.'
  },
  {
    UUID: 'Repair',
    Name: 'Repair (Assassin/Light Sorcery)',
    AP: 3,
    FP: 4,
    Cost: 1,
    Range: '5 foot range',
    Requirements: '13 Int requirement.',
    Description: 'Run your casting implement over an object no larger than a person or colossal weapon to deposit a powder of time bending light. This powder fully restores any durability loss to a piece of equipment, and repairs any damage or wear to the target object. Charging this spell lowers its FP cost by 2.'
  },
  {
    UUID: 'Hidden_Body',
    Name: 'Hidden Body (Assassin/Light Sorcery)',
    AP: 3,
    FP: 4,
    Cost: 1,
    Range: '5 foot range',
    Duration: '4 round duration.',
    Requirements: '14 Int requirement.',
    Description: 'Bend the light across your body, or another willing creatures body in range. The targets body and armor are enveloped by a shimmering translucence, making them hard to see and increasing their stealth by +8 for the duration of the spell. This spell lasts four rounds (24 seconds). Charging this spell doubles its duration.'
  },
  {
    UUID: 'Twisted_Haze_of_Light',
    Name: 'Twisted Haze of Light (Assassin/Light Sorcery)',
    AP: 3,
    FP: 2,
    Cost: 1,
    Range: '5 foot range',
    Duration: '1 round duration.',
    Requirements: '16 Int requirement.',
    Description: 'Create a haze of twisted light around yourself or a willing creature in range for one full round. Any creature surrounded by the haze may predict any incoming offensive, projectile-based, spell that hits them according to the rules of the Parry weapon skill. If they are correct then the spell is reflected back at the attacker. Reflected spells deal an additional 1d4 poise damage. Charging this spell twists the haze into a wormhole, allowing the creature it surrounds to also predict non-projectile offensive spells. Although, doing so does not reflect them, it instead absorbs them into the haze and negates them.'
  },
  {
    UUID: 'Canon_of_Larossa',
    Name: 'Canon of Larossa (Assassin/Light Sorcery)',
    AP: 3,
    FP: 6,
    Cost: 2,
    Range: '35 foot range',
    Duration: '1 round duration.',
    Requirements: '3d12 magic damage, 17 Int requirement.',
    Description: 'Conjure a portal above yourself and fire a thick blue magical cannonball into it. Over the duration of the spell the cannonball lingers undetectable, until you choose to re summon it at any time, somewhere you can see within the spells range of where it was first conjured. The ball then falls out of a new portal onto the target location, impacting and damaging any creature it hits in that space. \par Only one instance of this spell may be active at a time, and casting a new one dissipates the old. Waiting the entire duration of the spell without re summoning the ball dissipates it, causing it to no longer be summonable. Charging this spell increases the range it can be summoned in by 10 feet, and inflicts the dazed status condition on any creatures it hits if they fail a DC (12 + your Int mod) diplomacy check.'
  },
  {
    UUID: 'Cosmic_Image',
    Name: 'Cosmic Image (Cosmic Sorcery)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '12 Int requirement.',
    Description: 'Move your casting implement in a fast and jagged circle to cause dimensional cracks which ward away distractions and allow one to attune to strange influence in a unoccupied target grid space. You may only have one of these spaces active at a time and creating a second cause the first to dissipate. While standing fully within the space any and all creatures receive +4 to their knowledge of cosmic influence skill, -2 to their sanity, and are able to more clearly perceive anomalous entities who are… imperceptible. \par Attempting to charge this spell causes strange effects on its caster that are not well understood. These effects often manifest as blood dripping from the eyes, nose, or mouth, visions of nonsensical events, hearing voices, losing memories, or gaining memories of events that have not taken place.'
  },
  {
    UUID: 'Void_Meteorite',
    Name: 'Void Meteorite (Cosmic Sorcery)',
    AP: 3,
    FP: 2,
    Cost: 1,
    Range: '30 foot range',
    Damage: '1d8 magic and 1d6 dark damage',
    Requirements: '15 Int requirement.',
    Description: 'Fire a small and dark cosmic projectile which flies toward a target in range. This projectile cannot be seen by the target is was cast towards but can be seen by all others. The damage scaling of the spell is split evenly between its magic and dark damage. If it cannot be split evenly then the scaling favors the magic damage over the dark. Charging this spell only adds damage die to its magic damage. Charging this spell also causes it to no longer cost FP and be immune to being parried or reflected.'
  },
  {
    UUID: 'Devorac_Nebulous_Butterfly',
    Name: 'Devorac\'s Nebulous Butterfly (Cosmic Sorcery)',
    AP: 5,
    FP: 4,
    Cost: 1,
    Range: '25 foot range',
    Duration: '3 round duration.',
    Requirements: '16 Int requirement.',
    Description: 'Conjure a nebulous and imploding butterfly that floats above your head for three rounds. As a reaction, you may send the butterfly toward any unoccupied space in range where it implodes and creates a small ephemeral wormhole. The wormhole turns to face a creature within 10 feet, forcing them to immediately make a DC (12 + your Int mod) athletics check or be pulled one space toward it. You may then choose to repeat the pull once more, on the same or another creature within 10 feet, before the wormhole disappears. A creature that is pulled while it is making a melee range attack has the target spaces of its attack also moved in the same direction. You may only have one conjured nebulous butterfly active at a time. Charging this spell increases its DC by 2 and allows the wormhole to make an additional pull if you so choose.'
  },
  {
    UUID: 'Void_Comet',
    Name: 'Void Comet (Cosmic Sorcery)',
    AP: 4,
    FP: 3,
    Cost: 1,
    Range: '40 foot range',
    Damage: '2d10 magic and 2d8 dark damage',
    Requirements: '17 Int requirement.',
    Description: 'Fire a dark cosmic projectile which flies toward a target in range. This projectile cannot be seen by the target is was cast towards but can be seen by all others. The damage scaling of the spell is split evenly between its magic and dark damage. If it cannot be split evenly then the scaling favors the magic damage over the dark. Charging this spell only adds damage die to its magic damage. Charging this spell also causes it to no longer cost FP and be immune to being parried or reflected.'
  },
  {
    UUID: 'Cascade_Wave',
    Name: 'Cascade Wave (Cosmic Sorcery)',
    AP: 4,
    FP: 4,
    Cost: 1,
    Range: '30 foot range',
    Damage: '4d8 magic damage',
    Requirements: '18 Int requirement.',
    Description: 'Send a 15 foot long wave of cosmic light forward which stretches from diagonally to your left, to diagonally to your right. This wave travels forward hitting all it its path until it strikes a creature or obstacle with its middle space, or reaches its maximum range. The curvature of the wave prevents any creature from dodging it if they dodge in any direction except opposite the waves movement (if they were already within the spells area of effect). Charging this spell causes it to stretch an additional 5 feet left and right, and causes it to travel 10 feet farther.'
  },
  {
    UUID: 'Darkmoon_of_Luna',
    Name: 'Darkmoon of Luna (Cosmic Sorcery)',
    AP: 8,
    FP: 5,
    Cost: 2,
    Range: '80 foot range',
    Damage: '4d8 magic and 3d8 dark damage',
    Requirements: '20 Int requirement.',
    Description: 'Float up to ten feet into the air and curl your body to create a large celestial projectile in your place, before launching it forward toward a target of your choice, and landing yourself back on the ground. The projectile can target any creature or object in range and homes in on them. Every round of combat on the start of your turns, and when you first fire the projectile, it moves three grid spaces (15 feet) directly toward the chosen target. This movement continues until the projectile is intercepted (as described in the Intercept feat), or it impacts a creature and/or your target. Any creature hit by this spell takes its damage and must make a DC (13 + your Int mod) sanity check or be inflicted with the dazed status condition. \par The projectile is unaffected by cover and can move through any non siderite material. You may have only one of these projectiles active at a time, and casting a new one dissipates the old. The damage scaling of the spell is split evenly between its magic and dark damage. If it cannot be split evenly then the scaling favors the magic damage over the dark. Charging this spell only adds damage die to its magic damage. Charging this spell also causes it to travel four grid spaces per turn instead of three, and causes it to explode on impact also hitting all grid spaces adjacent to the impact space.'
  },
  {
    UUID: 'Satellite_Eye',
    Name: 'Satellite Eye (Cosmic Sorcery)',
    AP: 6,
    FP: 5,
    Cost: 2,
    Range: '50 foot range',
    Damage: '8d8 magic damage',
    Requirements: '22 Int requirement.',
    Description: 'Summon a cosmic orb to fall from the sky on a target in range, and all grid spaces within 10 feet of it. The Orb impacts all creatures in the effected area dealing magic damage and inflicting the dazed status condition if they fail a DC (13 + your Int mod) sanity check. Any creature that rolls a one on the die of their sanity check is also inflicted by the frenzy status condition for one turn, immediately before taking the damage of the spell (some creatures are immune to this additional effect). \par This spell fails if cast indoors, and inflicts damage to cosmic entities as though they have been hit by siderite. Charging this spell causes it to instead hit all grid spaces within either 15 or 20 feet of your target, based on your choice (the choice must be made at the start of charging the spell, not when it resolves).'
  },
  {
    UUID: 'Teleport',
    Name: 'Teleport (Cosmic Sorcery)',
    AP: 7,
    FP: 10,
    Cost:  2,
    Range: '10 foot range',
    Requirements: '22 Int requirement.',
    Description: 'Teleport yourself and any willing creatures within 10 feet to any location you know of. Roll a d100 and if the result is greater than the DC of 70 then the spell succeeds and you are transported to the location. If you roll less than 10, or something about the location is incorrect/inconsistent/inaccurate, you and all allies that the spell was affecting are inflicted by the status condition frenzy until the next time you take a bonfire rest, and you all roll (4d2-4) and take that many points of exhaustion. \par The DC is lowered by 10 if you know what the location looks like, you have had the location described to you accurately, or if you know its exact distance from your current location. The DC is lowered by an additional 20 if you have been to the location, or have an object that once natively resided in that location. The DC is lowered by an additional 30 if you have taken multiple long rests at the location or have been there more than five separate times for at least a day in/day out each. \par In combat this spell take two rounds to cast and is interrupted if you take any damage (you cannot make any other actions on those rounds). If this spell fails it cannot be cast again for 1d4 hours. This spell cannot be charged.'
  },
  {
    UUID: 'Great_Satellite_Massive',
    Name: 'Great Satellite Massive (Cosmic Sorcery)',
    AP: '3h',
    FP: 15,
    Cost: 3,
    Range: 'Sight range',
    Damage: '15d20 magic and 15d20 physical damage',
    Requirements: '25 Int requirement.',
    Description: 'A forbidden spell of cosmic destruction. Summon a massive cosmic entity which impacts an area on the ground that you can see outside, before disappearing. All creatures within five kilometers (approx 3 miles) of the impact location are knocked prone, take the magic damage of the spell then the physical damage, and if they are dropped to zero HP by either source of damage are instantly vaporized and cannot respawn regardless of undying. Casting this spell leaves a five kilometer radius and 100 foot deep crater in its impact location, and destroys all non siderite within the area. \par The moment this spell resolves, but before impact, make a DC 30 knowledge of cosmic influence skill check. Failing this check causes your head to melt, and permanently kills you regardless of undying. The damage dealt by this spell is as though it was from a source of siderite. This spell can be interrupted by taking damage or being moved while casting. This spell cannot be charged.'
  },
  {
    UUID: 'Deep_Soul',
    Name: 'Deep Soul (Dark Hex)',
    AP: 2,
    FP: 1,
    Cost: 1,
    Range: '20 foot range',
    Damage: '1d6 dark damage',
    Requirements: '12 Int requirement.',
    Description: 'Fire a ball of dark soul dregs at a target in range. Charging this spell Increases its range by 10 feet.'
  },
  {
    UUID: 'Great_Deep_Soul',
    Name: 'Great Deep Soul (Dark Hex)',
    AP: 2,
    FP: 2,
    Cost: 1,
    Range: '20 foot range',
    Damage: '2d10 dark damage',
    Requirements: '16 Int and 10 Fai requirements.',
    Description: 'Fire a ball of powerful dark soul sediment at a target in range. Charging this spell Increases its range by 10 feet.'
  },
  {
    UUID: 'Great_Soul_Dregs',
    Name: 'Great Soul Dregs (Dark Hex)',
    AP: 4,
    FP: 3,
    Cost: 2,
    Range: '30 foot range',
    Damage: '6d10 dark damage',
    Requirements: '20 Int and 14 Fai requirements.',
    Description: 'Fire a massive projectile of dark soul dregs which have stewed for ages, at a target in range. Charging this spell increases its range by 10 feet, and once per charged casting causes it to change direction and follow a target that dodged out of its way, as long as it still has the range to do so.'
  },
  {
    UUID: 'Pursuing_Manifestations',
    Name: 'Pursuing Manifestations (Dark Hex)',
    AP: 8,
    FP: 5,
    Cost: 1,
    Range: '20 foot range',
    Duration: '10 round duration.',
    Requirements: '1d10 dark damage, 18 Int and 12 Fai requirements.',
    Description: 'Conjure three dark manifestations of humanity which stay floating above your head for the duration of the spell. You may choose to fire any number of them at any target space in range, during your own turn, for no additional AP or FP cost. Each manifestation deals the dark damage of this spell, with the total scaling split between them. Charging this spell adds a fourth manifestation, but does not add extra damage die to the individual manifestations.'
  },
  {
    UUID: 'Torrential_Deep',
    Name: 'Torrential Deep (Dark Hex)',
    AP: 4,
    FP: 4,
    Cost: 1,
    Range: '15 foot range',
    Duration: '3 round duration.',
    Damage: '2d6 dark damage',
    Requirements: '16 Int and 10 Fai requirements.',
    Description: 'Fire a small dark bead up into the air above a space in range. The bead then bursts and rains down darkness, hitting all grid spaces in a 10ft by 10ft area of your choice below it. The rain lasts for 3 rounds (18 seconds), and deals its dark damage upon casting and at the start of each of your turns to all creatures within the area. This spell does not stack with itself in a single area, but can be cast up to three times without dissipating its other instances. Charging this spell increases its range by 15 feet, and its duration by one round.'
  },
  {
    UUID: 'Dark_Storm',
    Name: 'Dark Storm (Dark Hex)',
    AP: 5,
    FP: 4,
    Cost: 2,
    Range: '20 foot range',
    Damage: '4d8 dark damage',
    Requirements: '18 Int and 12 Fai requirements.',
    Description: 'Conjure a hail of dark masses on a 10ft by 10ft area which makes contact with a grid space in range. All creatures within the area take the dark damage of this spell. Charging this spell increases the area to 15ft by 15ft, and increases its range by 10 feet.'
  },
  {
    UUID: 'Dark_Edge',
    Name: 'Dark Edge (Dark Hex)',
    AP: 4,
    FP: 1,
    Cost: 1,
    Range: '5 foot range',
    Damage: '1d8 dark damage',
    Requirements: '14 Int and 10 Fai requirements.',
    Description: 'Conjure a blade of humanities darkness out of your staff and swing it at a target in range. This blade may take the form of a katana or curved sword, and attacking with this spell also counts as using a Katana/Curved Sword for the sake of weapon feats. Charging this spell allows it to pierce one tier of dark resistance, and causes it to do 4 poise damage to any creature it hits.'
  },
  {
    UUID: 'Eye_of_the_Abyss',
    Name: 'Eye of the Abyss (Debuffing Hex)',
    AP: 5,
    FP: 6,
    Cost: 2,
    Range: '15 foot range',
    Duration: '5 round duration.',
    Requirements: '16 Int and 13 Fai requirements.',
    Description: 'Choose a target in range that you can see, they must make a DC (12 + your Int or Fai mod) sanity check or have their left eye swollen with darkness and be unable to be closed. Your left eye also swells with darkness and you can now see what they see through their eye. You are both inflicted with impaired vision, but every time they make a weapon attack you gain 1 AP for your next turn, every time they cast a spell or use a weapon skill you gain 1 FP, and every time they heal you gain 1d8 HP. Casting this on a new creature overwrites the first. \par Once per round at any time you may make the effected creature drop an abyssal tear onto their grid space, which lasts the duration of this casting of the spell. Anyone that moves through, begins, or ends their turn on that grid space takes 1d8 dark damage. This counts as a special magical effect on the target creature and can be dispelled. Charging this spell increases its DC by 3.'
  },
  {
    UUID: 'Corrupted_Blood_Dregs',
    Name: 'Corrupted Blood Dregs (Blood Hex)',
    AP: 3,
    FP: 1,
    Cost: 1,
    Range: '20 foot range',
    Requirements: '14 Int and 12 Fai requirements.',
    Description: 'Use your spell casting implement to magically draw out a portion of your own blood, dealing 5 true damage to yourself. Then, form the blood into an accursed mass and fire it as a physical projectile toward a target in range. Any creature hit by the projectile has its dark damage resistance lowered by one tier for the next ten minutes. This spell does not stack with itself. Charging this spell causes it to deal 1d4 bleed build up and lower dark resistance by two tiers.'
  },
  {
    UUID: 'Faces_of_Malice',
    Name: 'Faces of Malice (Death Hex)',
    AP: 3,
    FP: 3,
    Cost: 1,
    Range: '20 foot range',
    Damage: '4d6 dark damage',
    Requirements: '14 Int and 11 Fai requirements.',
    Description: 'With a small explosion of ghostly white fire, conjure four skulls of malice. Each skull may be sent toward any target space in range, and each d6 corresponds to an individual skull. Scaling bonus damage is evenly split between each skull. Charging this spell increases the number of skulls by two (but does not increase the damage of each individual skull) and causes each skull to also deal 1d2-1 poise damage. Multiple skulls hitting the same target do not count as separate instances of poise damage.'
  },
  {
    UUID: 'Ghostflame_Weapon',
    Name: 'Ghostflame Weapon (Death Hex)',
    AP: 3,
    FP: 4,
    Cost: 1,
    Range: '5 foot range',
    Duration: '5 round duration.',
    Requirements: '16 Int and 10 Fai requirements.',
    Description: 'Run your casting implement along a melee weapon in range to buff it with white ghostflame. The wielder of that weapon may add 2d4 dark damage (plus your scaling from this spell) and 2d2 frost status build up as a bonus, once per round to each creature that they damaged with that weapon. This buff lasts for five rounds (30 seconds). Charging this spell doubles its duration, but does not increase the damage of the buff.'
  },
  {
    UUID: 'Aspir_Glaive',
    Name: 'Aspir Glaive (Death Hex)',
    AP: 6,
    FP: 1,
    Cost: 2,
    Range: '20 foot range',
    Duration: '5 round duration.',
    Requirements: '20 Int and 16 Fai requirements.',
    Description: 'Send a conjured dark executioners glaive at a target in range. Any creature hit by the glaive must make a DC (12 + your Int mod) sanity and athletics check. If they fail they lose 2d4 FP, and 2d12 HP respectively. Any FP, or HP they lose is then gained by you. Charging this spell causes any creature hit to also have to make a DC (12 + your Int mod) acrobatics check or take 1d4 poise damage. It also increases the DC of the sanity and athletics checks by 2.'
  },
  {
    UUID: 'Bent_Time',
    Name: 'Bent Time (Time Magic)',
    AP: 7,
    FP: 10,
    Cost:  2,
    Range: '15 foot range',
    Requirements: '22 Int requirement.',
    Description: 'Choose a target in range, they must make a DC (12 + your Int mod) acrobatics or sanity check. If they fail then they are sent forward in time by one full round, disappearing and then reappearing one round after the spell was cast, on the turn it was cast. Charging this spell causes the target to instead appear two rounds later.'
  },
  {
    UUID: 'Devorac_Timewarped_Butterfly',
    Name: 'Devorac\'s Timewarped Butterfly (Time Magic)',
    AP: 5,
    FP: 5,
    Cost: 2,
    Range: '25 foot range',
    Requirements: '22 Int requirement.',
    Description: 'Send out a conjured group of temporal and distorted butterflies which heal one point of exhaustion, and turn back a fragment of time, for their target the first time this is cast on that target in a day. \par Upon casting, choose one or more of the following effects to take place as a result of that fragment of time being turned back: allow the target to set their HP back to what is was one round ago, set their FP back to what it was one round ago, heal any poise damage done to them over the last round (potentially curing a stagger), or reset their position to what is was one round ago (causing them to instantly warp back through their path to that position, as long as the final position is unobstructed). Charging this spell allows all of its effects to reverse to up to two rounds ago, instead of just one.'
  }
]